"""empty message

Revision ID: 0f1a402f94e4
Revises: a1c4da94a9a4
Create Date: 2025-10-06 14:05:55.641139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f1a402f94e4'
down_revision = 'a1c4da94a9a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('premium_expires_at', sa.DateTime(), nullable=True))
        batch_op.create_index('idx_profile_premium', ['premium'], unique=False)
        batch_op.create_index('idx_profile_premium_expires', ['premium_expires_at'], unique=False)
        batch_op.create_index('idx_profile_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index('idx_profile_user_id')
        batch_op.drop_index('idx_profile_premium_expires')
        batch_op.drop_index('idx_profile_premium')
        batch_op.drop_column('premium_expires_at')

    # ### end Alembic commands ###
