"""changes

Revision ID: 2ed1e6e6ad01
Revises: f5a1e96f7791
Create Date: 2025-10-02 17:08:41.208983

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector  # ✅ import Vector directly


# revision identifiers, used by Alembic.
revision = '2ed1e6e6ad01'
down_revision = 'f5a1e96f7791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', Vector(dim=1536), nullable=True))  # ✅ fixed

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###
