"""changes

Revision ID: a1c4da94a9a4
Revises: 2ed1e6e6ad01
Create Date: 2025-10-02 17:53:46.298765

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector  # ✅ import Vector


# revision identifiers, used by Alembic.
revision = 'a1c4da94a9a4'
down_revision = '2ed1e6e6ad01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column(
            'embedding',
            existing_type=Vector(dim=1536),  # ✅ old type
            type_=Vector(dim=768),           # ✅ new type
            existing_nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column(
            'embedding',
            existing_type=Vector(dim=768),   # ✅ rollback
            type_=Vector(dim=1536),
            existing_nullable=True
        )

    # ### end Alembic commands ###
